spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itsc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Wc123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  ai:
    anthropic:
      api-key: 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
      chat:
        options:
          model: claude-3-haiku-20240307
          temperature: 0.7
          max-tokens: 450
        enabled: true

server:
  port: 8081
